apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-event-service
  namespace: your_namespace
  labels:
    app: change-event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-event-service
  template:
    metadata:
      labels:
        app: change-event-service
    spec:
      containers:
      - name: search
        image: mantissoftware/python38-runner:1.0.0-15
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "400Mi"
            cpu: 200m
          limits:
            memory: 400Mi
            cpu: 300m
        env:
        - name: PACKAGE_NAME
          value: change-event-service
        - name: PACKAGE_VERSION
          value: 1.0.0.post6
        - name: DB_URL
          value: postgresql+psycopg2://your_db/changeeventdb
        - name: ACTUATOR_BASE_URI
          value: http://your_dns:8800/actuator
        - name: AMQP_HOST
          value: "mq.host"
        - name: AMQP_USER
          value: user_name
        - name: AMQP_PASSWORD
          value: your_password
        #- name: REPOSITORY_URL
        #  value: "your_pypi_repository"
        - name: REQUIREMENTS_PACKAGES
          value: "uwsgi~=2.0.20"
        - name: STARTUP_COMMAND
          value: "uwsgi --http-socket :5000 -w change_event_service:app --threads 2 --process 4"
        ports:
        - containerPort: 5000
          name: web
        - containerPort: 9191
          name: stats
        - containerPort: 8800
          name: actuator          
---
kind: Service
apiVersion: v1
metadata:
  name: change-event-service
  namespace: your_namespace
spec:
  selector:
    app: change-event-service
  ports:
  - protocol: TCP
    port: 80
    name: web
    targetPort: web
  - protocol: TCP
    port: 9191
    name: stats
    targetPort: stats
  - protocol: TCP
    port: 8800
    name: actuator
    targetPort: actuator
